"""Constants for the Diagral e-one API."""

from typing import Final

BASE_URL = "https://appv3.tt-monitor.com/topaze"
HTTP_CALL_TIMEOUT: Final[int] = 45

SESSION_ID = "sessionId"
DIAGRAL_ID = "diagralId"
USERNAME = "username"
COUNTRY = "country"
USER_TYPE = "userType"
EXPIRES_IN = "expiresIn"
SYSTEMS = "systems"
SYSTEM_ID = "systemId"
ROLE = "role"
TRANSMITTER_ID = "transmitterId"
CENTRAL_ID = "centralId"
INSTALLATION_COMPLETE = "installationComplete"
NAME = "name"
ROLE = "role"
ID = "id"
STANDALONE = "standalone"
IS_CONNECTED = "isConnected"
MESSAGE = "message"
TTM_SESSION_ID = "ttmSessionId"
SYSTEM_STATE = "systemState"
GROUPS = "groups"
GROUP_LIST = "groupList"
STATUS = "status"
CONNECTED_USER_TYPE = "connectedUserType"
CODE_INDEX = "codeIndex"
DEFAULTS = "defaults"
COMMAND_STATUS = "commandStatus"
