name: Upload Python Package to PyPI when a tag is Created

on:
    push:
      tags:
        - "v*.*.*"
jobs:
  build_and_publish:
    name: Publish a new version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Flit
        run: |
          python -m pip install --upgrade pip
          pip install flit

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publish Package to PyPI
        env:
          FLIT_USERNAME: '__token__'
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          flit publish